### ISSUE TITLE
Issue in verify.py file execution

### ISSUE THREAD

**Issue by Ravihari123** [jankrepl/mildlyoverfitted#1] opened 2021-08-29 14:31 UTC
Thank you for the codes and video explanation. I got the following issue while running the verify.py file. I could run custom.py without any error and I have installed python 3.9, PyTorch version 1.8. 
I did all the verification related to the availability of the vit_base_patch16_384 patch in the vision_transformer.py file. This is the error I got. 
Could you please help me to solve this issue? 
![Issue](https://user-images.githubusercontent.com/88596985/131253943-55e8b5db-ecae-4d56-a5f2-f43d2d0b5ed6.PNG)

**Comment by jankrepl** [comment] 2021-08-29 15:11
Hey there and thanks for you interest!


I am not able to reproduce it on my computer. However, looking at your tracebook it seems like the following should reproduce your error. Could you try it?

```bash
python -c 'import timm;timm.create_model("vit_base_patch16_384", pretrained=True)'
```

If it is the case maybe your checkpoint is corrupted (my best guess). I would suggest you just delete it and retrigger a new download. On my computer it is stored under
```
$HOME/.cache/torch/hub/checkpoints/B_16-i21k-300ep-lr_0.001-aug_medium1-wd_0.1-do_0.0-sd_0.0--imagenet2012-steps_20k-lr_0.01-res_384.npz
```
(`HOME` is the home folder). Once you delete it, try running the above code snippet again and maybe this time around it is gonna work:)

**Comment by Ravihari123** [comment] 2021-08-29 18:43
It worked!! Thank you very much :)

**Comment by jankrepl** [comment] 2021-08-29 18:56
Perfect! I am closing this issue then!

**Closed by jankrepl** 2021-08-29 18:56 UTC
